INSERT INTO [dbo].[Editora] (Nome_Editora, Info_Editora, Img_Editora) VALUES
('Porto Editora', 'Uma das maiores editoras de Portugal, com um vasto catálogo em diversas áreas.', 'editorasemfoto.png'),
('Leya', 'Grupo editorial com forte presença no mercado português, publicando autores nacionais e internacionais.', 'editorasemfoto.png'),
('Editorial Presença', 'Editora focada em ficção, tanto para adultos como para jovens.', 'editorasemfoto.png'),
('Gradiva', 'Publicações nas áreas de ciência, filosofia e literatura.', 'editorasemfoto.png'),
('Dom Quixote', 'Editora com um catálogo diversificado, incluindo ficção, não-ficção e poesia.', 'editorasemfoto.png'),
('Relógio D''Água', 'Editora independente com foco em literatura de qualidade.', 'editorasemfoto.png'),
('Quetzal Editores', 'Publica autores contemporâneos e clássicos da literatura.', 'editorasemfoto.png'),
('Bertrand Editora', 'Uma das editoras mais antigas de Portugal, com um vasto catálogo.', 'editorasemfoto.png'),
('Saída de Emergência', 'Especializada em literatura fantástica e ficção científica.', 'editorasemfoto.png'),
('Edições 70', 'Publicações nas áreas de ciências sociais, humanidades e artes.', 'editorasemfoto.png'),
('Objectiva', 'Parte do grupo Penguin Random House, publica autores de renome internacional.', 'editorasemfoto.png'),
('Tinta-da-China', 'Editora independente com um catálogo eclético e inovador.', 'editorasemfoto.png'),
('Guerra & Paz', 'Editora focada em história, política e atualidade.', 'editorasemfoto.png'),
('Editorial Caminho', 'Publica literatura portuguesa e traduzida, bem como livros infantis.', 'editorasemfoto.png'),
('Livros do Brasil', 'Editora histórica, com um catálogo que inclui clássicos da literatura universal.', 'editorasemfoto.png'),
('Alfaguara', 'Parte do grupo Penguin Random House, publica autores de língua portuguesa e espanhola.', 'editorasemfoto.png'),
('Editora Imaginarium', 'Editora fictícia especializada em livros ilustrados para crianças.', 'editorasemfoto.png'),
('Letras & Cores', 'Editora fictícia dedicada à publicação de romances.', 'editorasemfoto.png'),
('Mundo dos Livros', 'Editora fictícia com um catálogo diversificado de ficção e não-ficção.', 'editorasemfoto.png'),
('Estrela Polar Editora', 'Editora fictícia focada em literatura de viagem e aventura.', 'editorasemfoto.png'),
('Lua Cheia Publicações', 'Editora fictícia especializada em poesia e contos.', 'editorasemfoto.png'),
('Sabedoria Antiga', 'Editora fictícia dedicada a livros sobre espiritualidade e autoconhecimento.', 'editorasemfoto.png'),
('Edições Aurora', 'Editora fictícia que publica ficção científica e fantasia.', 'editorasemfoto.png'),
('Horizonte Literário', 'Editora fictícia com foco em autores emergentes.', 'editorasemfoto.png'),
('Oásis Editorial', 'Editora fictícia que publica livros de arte e fotografia.', 'editorasemfoto.png');