INSERT INTO [dbo].[Generos] (Nome_Generos) VALUES
('Romance'),
('Ficção Científica'),
('Fantasia'),
('Mistério'),
('Thriller'),
('Suspense'),
('Terror'),
('Ficção Histórica'),
('Biografia'),
('Autobiografia'),
('Poesia'),
('Drama'),
('Comédia'),
('Aventura'),
('Ação'),
('Conto'),
('Ensaio'),
('Literatura Infantil'),
('Literatura Juvenil'),
('Distopia'),
('Realismo Mágico'),
('Fábula'),
('Crónica'),
('Epopeia'),
('Literatura de Viagem');