INSERT INTO [dbo].[Pais] (Nome_Pais) VALUES
('Portugal'),
('Espanha'),
('França'),
('Alemanha'),
('Itália'),
('Reino Unido'),
('Irlanda'),
('Países Baixos'),
('Bélgica'),
('Luxemburgo'),
('Suíça'),
('Áustria'),
('Dinamarca'),
('Suécia'),
('Noruega'),
('Finlândia'),
('Islândia'),
('Polónia'),
('República Checa'),
('Eslováquia'),
('Hungria'),
('Roménia'),
('Bulgária'),
('Grécia'),
('Chipre'),
('Malta'),
('Eslovénia'),
('Croácia'),
('Sérvia'),
('Bósnia e Herzegovina'),
('Montenegro'),
('Macedónia do Norte'),
('Albânia'),
('Estónia'),
('Letónia'),
('Lituânia'),
('Bielorrússia'),
('Ucrânia'),
('Moldávia'),
('Rússia'),
('Turquia'),
('Geórgia'),
('Arménia'),
('Azerbaijão'),
('Cazaquistão'),
('Brasil'),
('Argentina'),
('México'),
('Estados Unidos da América'),
('Canadá'),
('Austrália'),
('Nova Zelândia'),
('Japão'),
('China'),
('Índia'),
('Coreia do Sul'),
('Indonésia'),
('Filipinas'),
('Tailândia'),
('Vietname'),
('Malásia'),
('Singapura'),
('África do Sul'),
('Egito'),
('Nigéria'),
('Marrocos'),
('Argélia'),
('Tunísia'),
('Quénia'),
('Tanzânia'),
('Uganda'),
('Angola'),
('Moçambique'),
('Gana'),
('Costa do Marfim'),
('Senegal'),
('Camarões'),
('Zâmbia'),
('Zimbábue'),
('Ruanda'),
('Burundi'),
('Etiópia'),
('Sudão'),
('Somália'),
('Madagáscar'),
('Maurícia');