// <auto-generated />
using System;
using LibSpace.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibSpace.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241120103608_Favorito")]
    partial class Favorito
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeneroLivro", b =>
                {
                    b.Property<int>("IdGeneros")
                        .HasColumnType("int");

                    b.Property<int>("IdLivro")
                        .HasColumnType("int");

                    b.HasKey("IdGeneros", "IdLivro");

                    b.HasIndex("IdLivro");

                    b.ToTable("GeneroLivro");
                });

            modelBuilder.Entity("LibSpace.Models.Autor", b =>
                {
                    b.Property<int>("IdAutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Autor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAutor"));

                    b.Property<string>("Bibliografia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DataFalecimento")
                        .HasColumnType("date")
                        .HasColumnName("Data_Falecimento");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("Data_Nascimento");

                    b.Property<string>("FotoAutor")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Foto_Autor");

                    b.Property<int>("IdLingua")
                        .HasColumnType("int")
                        .HasColumnName("Id_Lingua");

                    b.Property<string>("NomeAutor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Nome_Autor");

                    b.Property<string>("Pseudonimo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdAutor");

                    b.HasIndex("IdLingua");

                    b.ToTable("Autor");
                });

            modelBuilder.Entity("LibSpace.Models.Biblioteca", b =>
                {
                    b.Property<int>("IdBiblioteca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Biblioteca");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBiblioteca"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(125)
                        .IsUnicode(false)
                        .HasColumnType("varchar(125)");

                    b.Property<string>("EndCodPostal")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("End_CodPostal");

                    b.Property<string>("EndMorada")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("End_Morada");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeBiblioteca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nome_Biblioteca");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("varchar(9)");

                    b.HasKey("IdBiblioteca");

                    b.HasIndex("EndCodPostal");

                    b.ToTable("Biblioteca");
                });

            modelBuilder.Entity("LibSpace.Models.Bloquear", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_User");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<DateOnly>("DataBloqueio")
                        .HasColumnType("date")
                        .HasColumnName("Data_Bloqueio");

                    b.Property<int>("IdAdmin")
                        .HasColumnType("int")
                        .HasColumnName("ID_Admin");

                    b.Property<string>("MotivoBloquear")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Motivo_Bloquear");

                    b.HasKey("IdUser");

                    b.ToTable("Bloquear");
                });

            modelBuilder.Entity("LibSpace.Models.CodigoPostal", b =>
                {
                    b.Property<string>("EndCodPostal")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("End_CodPostal");

                    b.Property<string>("EndLocalidade")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("End_Localidade");

                    b.HasKey("EndCodPostal");

                    b.ToTable("CodigoPostal");
                });

            modelBuilder.Entity("LibSpace.Models.Editora", b =>
                {
                    b.Property<int>("IdEditora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Editora");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEditora"));

                    b.Property<string>("ImgEditora")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("Img_Editora");

                    b.Property<string>("InfoEditora")
                        .HasColumnType("text")
                        .HasColumnName("Info_Editora");

                    b.Property<string>("NomeEditora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nome_Editora");

                    b.HasKey("IdEditora");

                    b.ToTable("Editora");
                });

            modelBuilder.Entity("LibSpace.Models.Escreveu", b =>
                {
                    b.Property<int>("IdLivro")
                        .HasColumnType("int")
                        .HasColumnName("ID_Livro");

                    b.Property<int>("IdAutor")
                        .HasColumnType("int")
                        .HasColumnName("ID_autor");

                    b.HasKey("IdLivro");

                    b.HasIndex("IdAutor");

                    b.ToTable("Escreveu");
                });

            modelBuilder.Entity("LibSpace.Models.Favorito", b =>
                {
                    b.Property<int>("IdLivro")
                        .HasColumnType("int")
                        .HasColumnName("ID_Livro");

                    b.Property<int>("IdLeitor")
                        .HasColumnType("int")
                        .HasColumnName("ID_Leitor");

                    b.HasKey("IdLivro", "IdLeitor");

                    b.ToTable("Favorito");
                });

            modelBuilder.Entity("LibSpace.Models.Genero", b =>
                {
                    b.Property<int>("IdGeneros")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Generos");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGeneros"));

                    b.Property<string>("NomeGeneros")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Nome_Generos");

                    b.HasKey("IdGeneros");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("LibSpace.Models.InserirLivro", b =>
                {
                    b.Property<int>("IdLivro")
                        .HasColumnType("int")
                        .HasColumnName("ID_Livro");

                    b.Property<int>("IdBibliotecario")
                        .HasColumnType("int")
                        .HasColumnName("ID_Bibliotecario");

                    b.HasKey("IdLivro");

                    b.ToTable("Inserir_Livro");
                });

            modelBuilder.Entity("LibSpace.Models.Livro", b =>
                {
                    b.Property<int>("IdLivro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Livro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLivro"));

                    b.Property<string>("CapaImg")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Capa_IMG");

                    b.Property<int>("Clicks")
                        .HasColumnType("int")
                        .HasColumnName("Clicks");

                    b.Property<DateOnly>("DataEdicao")
                        .HasColumnType("date");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ISBN");

                    b.Property<int>("NumExemplares")
                        .HasColumnType("int")
                        .HasColumnName("Num_Exemplares");

                    b.Property<string>("Sinopse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TituloLivros")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Titulo_Livros");

                    b.HasKey("IdLivro");

                    b.ToTable("Livro");
                });

            modelBuilder.Entity("LibSpace.Models.Pais", b =>
                {
                    b.Property<int>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Pais");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPais"));

                    b.Property<string>("NomePais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nome_Pais");

                    b.HasKey("IdPais");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("LibSpace.Models.Perfil", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_perfil");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPerfil"));

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("DataNascimentoPerfil")
                        .HasColumnType("date")
                        .HasColumnName("DataNascimento_Perfil");

                    b.Property<string>("EndCodPostal")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("End_CodPostal");

                    b.Property<string>("EndMorada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("End_Morada");

                    b.Property<string>("ImgPerfil")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("Img_Perfil");

                    b.Property<string>("NomePerfil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nome_Perfil");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.HasKey("IdPerfil");

                    b.HasIndex("EndCodPostal");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("LibSpace.Models.Publica", b =>
                {
                    b.Property<int>("IdLivro")
                        .HasColumnType("int")
                        .HasColumnName("ID_Livro");

                    b.Property<int>("IdEditora")
                        .HasColumnType("int")
                        .HasColumnName("ID_Editora");

                    b.HasKey("IdLivro");

                    b.HasIndex("IdEditora");

                    b.ToTable("Publica");
                });

            modelBuilder.Entity("LibSpace.Models.Requisita", b =>
                {
                    b.Property<int>("IdLeitor")
                        .HasColumnType("int")
                        .HasColumnName("ID_Leitor");

                    b.Property<int>("IdLivro")
                        .HasColumnType("int")
                        .HasColumnName("ID_Livro");

                    b.Property<DateTime>("DataRequisicao")
                        .HasColumnType("datetime")
                        .HasColumnName("Data_Requisicao");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("datetime")
                        .HasColumnName("Data_Entrega");

                    b.Property<DateOnly>("DataPrevEntrega")
                        .HasColumnType("date")
                        .HasColumnName("Data_PrevEntrega");

                    b.Property<int>("IdBibliotecarioRecetor")
                        .HasColumnType("int")
                        .HasColumnName("ID_BibliotecarioRecetor");

                    b.Property<int?>("IdBibliotecarioRemetente")
                        .HasColumnType("int")
                        .HasColumnName("ID_BibliotecarioRemetente");

                    b.HasKey("IdLeitor", "IdLivro", "DataRequisicao");

                    b.HasIndex("IdLivro");

                    b.ToTable("Requisita");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GeneroLivro", b =>
                {
                    b.HasOne("LibSpace.Models.Genero", null)
                        .WithMany()
                        .HasForeignKey("IdGeneros")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibSpace.Models.Livro", null)
                        .WithMany()
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibSpace.Models.Autor", b =>
                {
                    b.HasOne("LibSpace.Models.Pais", "IdLinguaNavigation")
                        .WithMany("Autors")
                        .HasForeignKey("IdLingua")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdLinguaNavigation");
                });

            modelBuilder.Entity("LibSpace.Models.Biblioteca", b =>
                {
                    b.HasOne("LibSpace.Models.CodigoPostal", "EndCodPostalNavigation")
                        .WithMany("Bibliotecas")
                        .HasForeignKey("EndCodPostal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EndCodPostalNavigation");
                });

            modelBuilder.Entity("LibSpace.Models.Escreveu", b =>
                {
                    b.HasOne("LibSpace.Models.Autor", "IdAutorNavigation")
                        .WithMany("Escreveus")
                        .HasForeignKey("IdAutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibSpace.Models.Livro", "IdLivroNavigation")
                        .WithOne("Escreveu")
                        .HasForeignKey("LibSpace.Models.Escreveu", "IdLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdAutorNavigation");

                    b.Navigation("IdLivroNavigation");
                });

            modelBuilder.Entity("LibSpace.Models.Favorito", b =>
                {
                    b.HasOne("LibSpace.Models.Livro", "IdLivroNavigation")
                        .WithMany("Favoritos")
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdLivroNavigation");
                });

            modelBuilder.Entity("LibSpace.Models.InserirLivro", b =>
                {
                    b.HasOne("LibSpace.Models.Livro", "IdLivroNavigation")
                        .WithOne("InserirLivro")
                        .HasForeignKey("LibSpace.Models.InserirLivro", "IdLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdLivroNavigation");
                });

            modelBuilder.Entity("LibSpace.Models.Perfil", b =>
                {
                    b.HasOne("LibSpace.Models.CodigoPostal", "EndCodPostalNavigation")
                        .WithMany("Perfils")
                        .HasForeignKey("EndCodPostal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EndCodPostalNavigation");
                });

            modelBuilder.Entity("LibSpace.Models.Publica", b =>
                {
                    b.HasOne("LibSpace.Models.Editora", "IdEditoraNavigation")
                        .WithMany("Publicas")
                        .HasForeignKey("IdEditora")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibSpace.Models.Livro", "IdLivroNavigation")
                        .WithOne("Publica")
                        .HasForeignKey("LibSpace.Models.Publica", "IdLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdEditoraNavigation");

                    b.Navigation("IdLivroNavigation");
                });

            modelBuilder.Entity("LibSpace.Models.Requisita", b =>
                {
                    b.HasOne("LibSpace.Models.Livro", "IdLivroNavigation")
                        .WithMany("Requisita")
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdLivroNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibSpace.Models.Autor", b =>
                {
                    b.Navigation("Escreveus");
                });

            modelBuilder.Entity("LibSpace.Models.CodigoPostal", b =>
                {
                    b.Navigation("Bibliotecas");

                    b.Navigation("Perfils");
                });

            modelBuilder.Entity("LibSpace.Models.Editora", b =>
                {
                    b.Navigation("Publicas");
                });

            modelBuilder.Entity("LibSpace.Models.Livro", b =>
                {
                    b.Navigation("Escreveu");

                    b.Navigation("Favoritos");

                    b.Navigation("InserirLivro");

                    b.Navigation("Publica");

                    b.Navigation("Requisita");
                });

            modelBuilder.Entity("LibSpace.Models.Pais", b =>
                {
                    b.Navigation("Autors");
                });
#pragma warning restore 612, 618
        }
    }
}
